apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-handler-7988
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-handler-7988
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
